### ISSUE TITLE
Need some help to run this

### ISSUE THREAD

**Issue by Jnkz** [glv2/bruteforce-wallet#10]
Hello, i'm writing to you because i'm not really confortable to use linux and i have a lot of difficulties to run this. I got a windows 10 pc, so i installed a virtual machine on it using Ubuntu. Butn when i follow all the step to configure, i got a lot of errors, i can't ./autogen.sh , ./configure and make install .  The errors coming, are "no permissions" "symbol not expected" "autoreconf not finded".
When i use ./configure, is not finding something to run, so i try ./configure.ac as the named file, and now is trying to run but i have the message "symbol not expected" (sorry for the translation of the errors messages)

What i have to do? I want to brute force my one year old ether wallet.

Thank's and sorry for my english

**Comment by glv2** [comment]
To compile the program on Ubuntu, you need to install some basic development packages:

    sudo apt install build-essential openssl-dev

However, this program only works for the wallet format used by Bitcoin-core and the crypto-currencies who forked the Bitcoin source code. It will not work with an Ethereum wallet because the source code base is different.

**Comment by Jnkz** [comment]
Ok, i saw another issue where was said something can be rewrited to run this for ethereum, but must be too hard for me. Do you know another program dedicated to ether wallets?

**Comment by adamgins** [comment]
@glv2 I am getting similar issue trying to install on Ubuntu - trying to recover lost litcoin password. 

```
ubuntu@ip-172-26-3-74:~/bruteforce-wallet-master$ sudo apt install build-essential libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.10).
0 upgraded, 0 newly installed, 0 to remove and 153 not upgraded.
ubuntu@ip-172-26-3-74:~/bruteforce-wallet-master$ 
```

**Comment by glv2** [comment]
@adamgins what is the error you get when trying to compile?
