### ISSUE TITLE
stop process and continue later

### ISSUE THREAD

**Issue by PhillRob** [glv2/bruteforce-wallet#12]
Is there a way to stop the process, and continue at the same progress later?

**Comment by glv2** [comment]
Currently, no.

**Comment by dogruis** [comment]
It would be useful to save the current status in a file so if the process is killed by mistake it can restart where it was.
Also it would be useful to have a print of the password currently tried to have an idea of what's going on

**Comment by glv2** [comment]
I added the options to print progress info regularly and to save/restore the state to/from a file (commit 2d0bef52774456f8f794186f80918e0f73714399).
