### ISSUE TITLE
I have Blockchain Wallet Backup "wallet.aes.json"

### ISSUE THREAD

**Issue by vido89** [glv2/bruteforce-wallet#13]
Does it work on Blockchain Wallet Backup "wallet.aes.json" ?
I did tried it but here is an error 

```
BDB0196 Encrypted checksum: no encryption key specified
BDB0196 Encrypted checksum: no encryption key specified
BDB0196 Encrypted checksum: no encryption key specified
BDB0196 Encrypted checksum: no encryption key specified
BDB0210 wallet.aes.json: metadata page checksum error
Error: wallet.aes.json.

: Invalid argument

```

**Comment by glv2** [comment]
This program only works with the *wallet.dat* file format created by bitcoin-qt (and coins that forked from the Bitcoin original code base).

**Comment by anderson6470** [comment]
@vido89 
I have recovered several blockchain wallet both first and secondary password. i can recover your wallet for you. you can contact me at : walletsrecoveryservice@gmail.com
