### ISSUE TITLE
Error wallet.dat. : Invalid argument

### ISSUE THREAD

**Issue by tomas223** [glv2/bruteforce-wallet#14]
Hi,
I successfully compiled code without issues but when i try to run it i get constantly same error:
```
Error: wallet.dat

: Invalid argument
```

I tried Ubuntu 14.04 and 16.04. BerkeleyDB 5.3 and 6.0 and also current version of bruteforce-wallet and also some older versions too.
Some long time ago my friend was able to start it on this same litecoin wallet file.

Can I provide any more info?
Thanks

**Comment by glv2** [comment]
What is the full command line you are using to call the program?

**Comment by tomas223** [comment]
Thank you for a quick reply.
Forgot to mention that. I tried following commands:
./bruteforce-wallet -t 4 -l 3 -m 5 wallet.dat
./bruteforce-wallet -t 8 -l 5 -m 10 -b "W4l" -e "z" wallet.dat
./bruteforce-wallet wallet.dat

**Comment by tomas223** [comment]
Please let me know if I can somehow turn on logging and post it here.
Thanks

**Comment by glv2** [comment]
I just pushed a commit improving some error messages when a file with an invalid format is passed to *bruteforce-wallet* (b7ac13d9b49e0e647271cf92eb55690990d6cf82). 

Could you compile the master branch and test it with your "wallet.dat" file?
