### ISSUE TITLE
Multibit support?

### ISSUE THREAD

**Issue by neilmunday** [glv2/bruteforce-wallet#15]
Hi,

Does your tool support Multibit (classic) wallet or key files?

I tried it with both but I got the following error:

$ ./bruteforce-wallet -l 3 -m 5
-t 2 ~/MultiBit/multibit.wallet
BDB0004 fop_read_meta: /home/neil/MultiBit/multibit.wallet:
unexpected file type or format
Error: /home/neil/MultiBit/multibit.wallet.

: Invalid argument

**Comment by glv2** [comment]
The program only works on wallet files using the "bitcoin-qt wallet.dat" format. The error message you got indicates that Multibit uses a different format.

**Comment by neilmunday** [comment]
Ok, no worries.

**Comment by anywalletrecovery** [comment]
@neilmunday 
I have machine for multibit wallet recovery and can recover wallet password
Telegram: @walletrecover

**Comment by anderson6470** [comment]
@neilmunday 
I can recover multibit wallet backup (old and new versions) if you haven't recover you can contact me walletsrecoveryservice@gmail.com
