### ISSUE TITLE
support for electracoin: 5203 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mehrunrasolian** [glv2/bruteforce-wallet#16]
Hi there :)

I have a wallet.dat file for my electracoin wallet which is encrypted with a pass-phrase.

If i try to btruteforce the file, I get the following error:
```bash
$ bruteforce-wallet -t 1 -l 6 wallet.dat

[1]    5970 segmentation fault (core dumped)  bruteforce-wallet -t 1 -l 6 wallet.dat
```

Here is a sample wallet.dat file with the pass-phrase 'secret' for test [wallet.dat.tar.gz](https://github.com/glv2/bruteforce-wallet/files/1610096/wallet.dat.tar.gz)

version 3.1 of the electracoin wallet on windows is used.

**Comment by glv2** [comment]
I was not able to reproduce your segmentation fault issue. On my system the program the password of your test *wallet.dat* file without error.

You could try running the program in *gdb* to see in which function the segmentation fault occurs.
