### ISSUE TITLE
How to use/run on UBUNTU?

### ISSUE THREAD

**Issue by mkvtvseries** [glv2/bruteforce-wallet#18]
I try installing n run it
but it seem not working for me
Kindly Help
please

**Comment by glv2** [comment]
Could you describe more precisely what your problem is?
What command(s) do you run? What error message(s) do you see?

**Comment by mkvtvseries** [comment]
From generating the configuration script, build the program & install on ubuntu

**Comment by mtmulch** [comment]
Hey @mkvtvseries try looking at my issue here. I am running Ubuntu 16.04 and was running into the same issue and was able to resolve it.
https://github.com/glv2/bruteforce-wallet/issues/20

**Comment by glv2** [comment]
@mkvtvseries the error message ```./autogen.sh: 6: ./autogen.sh: autoreconf: not found``` indicates that you are missing some software development packages. Try to install the *build-essentials* and *autoconf* packages.

**Comment by mkvtvseries** [comment]
Thank.
Updated
sudo apt-get update
sudo apt-get install libdb-dev
sudo apt-get install build-essential
sudo apt-get install autoconf

Got another Error:
XYZ55@ubuntutrial:~/bruteforce-wallet$ make install
make[1]: Entering directory '/home/XYZ55/bruteforce-wallet'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c bruteforce-wallet '/usr/local/bin'
/usr/bin/install: cannot create regular file '/usr/local/bin/bruteforce-wallet': Permission denied
Makefile:312: recipe for target 'install-binPROGRAMS' failed
make[1]: *** [install-binPROGRAMS] Error 1
make[1]: Leaving directory '/home/XYZ55/bruteforce-wallet'
Makefile:629: recipe for target 'install-am' failed
make: *** [install-am] Error 2

XYZ55@ubuntutrial:~/bruteforce-wallet$ sudo make install
make[1]: Entering directory '/home/XYZ55/bruteforce-wallet'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c bruteforce-wallet '/usr/local/bin'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/XYZ55/bruteforce-wallet'

**Comment by glv2** [comment]
Yes to install to the */usr/local/bin* directory you need to be *root*.

But you don't need to install the program to a system directory to use it. You can run it from the source directory:

    cd /home/XYZ55/bruteforce-wallet
    ./bruteforce-wallet [options...]

or

    /home/XYZ55/bruteforce-wallet/bruteforce-wallet [options...]

**Comment by mkvtvseries** [comment]
Thank @glv2 will check. 
Is there a way to use GPU?

**Comment by glv2** [comment]
There is no GPU support. The program uses the *openssl* library, which uses the CPU only.

**Comment by mkvtvseries** [comment]
Thank @glv2
