### ISSUE TITLE
Question: Rainbow Table

### ISSUE THREAD

**Issue by mtmulch** [glv2/bruteforce-wallet#19]
Hello sir,

Thanks putting this together. Currently trying to recover a lost Dogecoin wallet from years ago. I've tested your library out on the current Dogecoin core version wallet. And was able to recover it.  

I imagine you have a much better understanding of the cryptography behind this solution than I do. Is it possible to create a rainbow table from the hashes generated from each password? I am no C developer so as of right now, I cannot figure it out. 

Perhaps we could collaborate?

**Comment by glv2** [comment]
Each wallet file uses its own random 64-bit salt and number of rounds in addition to the user's password to encrypt its master key. This makes a rainbow table almost useless.

**Comment by mtmulch** [comment]
Fair enough I'll have to read into it a little more, I appreciate the information. For the moment I'm just enjoying the learning experience.
