### ISSUE TITLE
Issue: Dependencies

### ISSUE THREAD

**Issue by mtmulch** [glv2/bruteforce-wallet#20]
The following dependencies are listed in the read me. "libdb6.0-dev libssl-dev".

I am currently running Ubunut 16.04 and was unable to install "libdb6.0-dev". I resolved this by using 
"libdb-dev". After install that package I was able to successfully test a bruteforce a Dogecoin core wallet.

**Comment by glv2** [comment]
Fixed in commit 38bbd466980c50c8daa578040d670891c88a4bb9
