### ISSUE TITLE
tmp/cache file location

### ISSUE THREAD

**Issue by loebpaul** [glv2/bruteforce-wallet#22]
Hi, I was running this script for a few hours and now my hard disk is full. Is there a tmp/cache directory that I can clear?

Thank you!

**Comment by glv2** [comment]
I doubt that your full disk issue comes from *bruteforce-wallet*.
The only thing the program writes to disk is a small state file (less than 1 kB) if you use the *-w* option.

**Comment by loebpaul** [comment]
you're right, it was something else. thank you for the quick resposne!
