### ISSUE TITLE
Passphrase

### ISSUE THREAD

**Issue by randy111** [glv2/bruteforce-wallet#25]
Hello,

is it possible to use this for a passphrase? I have a seed (that is very likely correct) and a passphrase (that very likely contains one or several typos). 

Can i use this software for passphrases too?

**Comment by glv2** [comment]
No, this program is for encrypted *wallet.dat* files, not for encrypted seeds.

**Comment by randy111** [comment]
Is there another tool that could help with my problem?

**Comment by glv2** [comment]
I depends what the format of your seed is. You could check if [btcrecover](https://github.com/gurnec/btcrecover) could work in your case.

**Comment by anywalletrecovery** [comment]
@randy111 
I have machine for 25th word recovery and can recover wallet extra phrase
Telegram: @walletrecover

**Comment by anderson6470** [comment]
@randy111 
I can recover your passphrase if its not longer than 13 characters long you can reach me at:
walletsrecoveryservice@gmail.com
