### ISSUE TITLE
Please grant a license exemption for linking bruteforce-wallet against OpenSSL

### ISSUE THREAD

**Issue by fr4ncisco** [glv2/bruteforce-wallet#26]
I'm currently looking into packaging bruteforce-wallet for Debian.

Your code is under GPL and the GPL is incompatible with some terms of the OpenSSL license. This makes Debian (and probably other distributions, too) not allowing GPL-licensed code to be linked with OpenSSL libraries unless there is a license exception explicitly permitting this.

To grant such an exception, it should suffice to add these paragraphs to whereever the GPL preamble is used (and probably also to the LICENSE file):

> In addition, as a special exception, the copyright holders give permission to link the code of 
> portions of this program with the OpenSSL library under certain conditions as described in each 
> individual source file, and distribute linked combinations including the two.
> 
> You must obey the GNU General Public License in all respects for all of the code used other 
> than OpenSSL. If you modify file(s) with this exception, you may extend this exception to your 
> version of the file(s), but you are not obligated to do so. If you do not wish to do so, delete this 
> exception statement from your version. If you delete this exception statement from all source files 
> in the program, then also delete it here.

Alternatively (but surely more effort) would be to also support GnuTLS as alternative to OpenSSL.

**Comment by glv2** [comment]
I released version 1.5.3, for which I added the license exception for linking with OpenSSL.

**Comment by fr4ncisco** [comment]
Thanks!
