### ISSUE TITLE
Compilation error & feature request (pipe dictionary)

### ISSUE THREAD

**Issue by uFire** [glv2/bruteforce-wallet#28]
Hello

While trying to compile the source on the CentOS 7, I had to add a ``AM_PROG_CC_C_O`` to the line 8 of the configure.ac, otherwise it gave me an error. Hope this could help someone.

It would be nice to have an ability to pipe a dictionary to your tool in a single-threaded mode and save output to the file like: 

`$ ./my_words_generator | ./bruteforce-wallet -o output_file.txt -d wallet.dat`

This way user could have more control over process, could run multiple threads piping different word generators to each instance.

Thank you for a great tool - it helped me to recover the lost password.

**Comment by glv2** [comment]
The ```AM_PROG_CC_C_O``` should only be necessary for automake versions older than 1.14 according to the manpage.

You should be able to read candidates from standard input and save the output to a file with something like:
``` shell
./my_words_generator | bruteforce-wallet -f /dev/stdin wallet.dat > output_file.txt
```
