### ISSUE TITLE
state.txt not created,

### ISSUE THREAD

**Issue by dextronomous** [glv2/bruteforce-wallet#29]
hi there, i notice i can't get a state.txt file created or any other .txt with -w state.txt or any.
hope an easy fix. thanks

**Comment by glv2** [comment]
Did you let the program run at least one minute before checking the existence of the state file?
The state file is written every minute, so you have to wait at least one minute after starting the program for the state file to be created.

**Comment by dextronomous** [comment]
yes i did

**Comment by glv2** [comment]
I can't reproduce this issue. Could you give an example of command line you are using?
Also, did you check that you have write access to the directory where you try to create the state file?

**Comment by dextronomous** [comment]
./bruteforce-wallet -t 3 -l 8 -m 8 -e "111" -v 30 -w state.txt wallet.dat

**Comment by CryptoXploit** [comment]
its signaling issue.the tool author has defined ctrl+z instead of ctrl+c to terminate.once you terminate using ctrl+z it will create state.txt in the folder and you can resume the scanning later on.

**Comment by dextronomous** [comment]
oh great thanks for this information will help for sure.

**Comment by dextronomous** [comment]
ctrl+z did not work tried several minutes scanning few minutes, few times, but no file.
