### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by goldminers** [glv2/bruteforce-wallet#30]
I'm trying to add special characters in the configure file.

I added '!@#$' to as_cr_letters but I think it is getting rejected later in the program. I also tried adding it to as_cr_digits. Same results

**Comment by glv2** [comment]
If your purpose is to change the character set that will be used to bruteforce the password, you can either use the '-s' option when starting the program, or change the value of the ```default_charset``` variable near the top of 'src/bruteforce-wallet.c' and recompile.

**Comment by goldminers** [comment]
Thank you! adding the special characters to the default_charset worked.

**Comment by Original-Tasty** [comment]
Hi, i've added special characters and it worked.

However, there is a problem with the special character:  `\`

in fact the code simply ignores that special characters, i have no idea why ...

All others perfectly works, including that slash bar in the other way:  `/`
