### ISSUE TITLE
Autoreconf missing?

### ISSUE THREAD

**Issue by roadtripguy** [glv2/bruteforce-wallet#35]
I run the ./autogen.sh script and it returns an error saying it can't find autoreconf.  When looking at the script it looks like it is trying to call autoreconf but it does not exist in this source.

I am not very familiar with Linux but I know enough to get around.  So its possible I am doing something wrong.  But I do not see this file in GitHub either

**Comment by glv2** [comment]
*autoreconf* is a program that you must install on your machine. Your GNU/Linux distribution should be have an *autoconf* package that you can install.

If you're using a Debian-like distribution, try:
``` shell
apt install gcc binutils make autoconf automake autotools-dev
```

**Comment by Lionsara** [comment]
thank you.
