### ISSUE TITLE
Unable to use russian character set

### ISSUE THREAD

**Issue by Aidoneus** [glv2/bruteforce-wallet#4]
I'm trying to use russian symbols with -s key (original password probably contains some), and program tells me that there is no such file. Is there any way to use them?

**Comment by MrBrighty** [comment]
Have the same question. Is it possible to change default symbols?

**Comment by glv2** [comment]
I don't see any problem when trying to use russian characters. For example:

    bruteforce-wallet -m 2 -s "АБВГДЕЁЖЗИЙКЛ" /path/to/wallet.dat
    Tried passwords: 182
    Total space searched: 100,000000%
    Password not found

What is the locale of your system? (I'm using a utf-8 locale).
