### ISSUE TITLE
issue about ofdm-transfer

### ISSUE THREAD

**Issue by liiso7** [glv2/bruteforce-wallet#42]
hello,I have some questions about [.](https://github.com/glv2/ofdm-transfer) That project is read-only right now, so I'm here to ask you.

The problem page states that imprecise clocks can cause frequency offsets, If the offset between the center frequencies of the sender and the receiver is bigger than 1% of the OFDM signal bandwidth, the receiver will probably not be able to decode the frames. So I used the same external clock source to clock both BladerFs, but I didn't receive any data at the receiver.

When I'm not using an external clock source, I can see "Frame 1 for ' ' : corrupted payload" on the receiver. But the received file is empty.

I would like to ask what causes the failure of transmission and how I should adjust it. I look forward to your reply.

**Comment by glv2** [comment]
The repository for ofdm-transfer is at https://codeberg.org/glv/ofdm-transfer.

The failure to decode frames could be due to a too low gain. Have you check with a general SDR receiver (like gqrx) if you can clearly see the signal with the gain settings you chose?

**Comment by liiso7** [comment]
Yes, I used GQRX to check my transmit signal and it can see the signal on my transmit frequency. I also adjusted the gain but still couldn't decode the frame.
What is the format of your transfer file? Could you please provide me with your transfer files? Thank you very much!!

**Comment by glv2** [comment]
If your SDR devices have a noticeable DC spike, it could interfere with the decoding. In this case you should use offset tuning with the '-o' command line option.

**Comment by liiso7** [comment]
I used the '-o' command-line option and here are some of the arguments I used:
    ofdm-transfer -t \
                  -r driver=bladerf \
                  -s 4000000 \
                  -f 434000000 \
                  -o 100000 \
                  -b 38400 \
                  -g 60 \
                  -w 1 \
                  -v \

    ofdm-transfer -r driver=bladerf \
                  -s 4000000 \
                  -f 434000000 \
                  -o 100000 \
                  -b 38400 \
                  -g 60 \
                  -w 1\
                  -T 30 \
                  -v

**Comment by liiso7** [comment]
I used the following command to perform the ofdm test without SDR:
TX : `ofdm-transfer -t  -r file=/tmp/samples.dat   -s 4000000   -f 434000000   -o 0    -b 38400   -g 60                   -w 1  -v  -a   '/home/ss/Linux-OFDM/ofdm_loopback05_Rx_Vector_Source.sc16q11' 
`
RX : `ofdm-transfer -r file=/tmp/samples.dat   -s 4000000  -f 434000000    -o 0  -b 38400   -g 60   -w 1                  -T 30   -v   sample_rx.dat
`
I stored the sent data in '/tmp/samples.dat' file and read the data from this file for ofdm demodulation, as a result I did not demodulate any data on rx. What's wrong with me doing this? Why don't we get any data?Looking forward to your reply！
