### ISSUE TITLE
Android Bitcoin Wallet

### ISSUE THREAD

**Issue by bitnapper** [glv2/bruteforce-wallet#6]
I tried it with a wallet backup from [Bitcoin Wallet](https://play.google.com/store/apps/details?id=de.schildbach.wallet) for Android but it ends with an error: 

`Error: wallet.dat.`

I guess this format is not supported. Would it be possible to add support for this format.

**Comment by elkiwi** [comment]
I'm trying with an Android app backup wallet too but get:

sudo bruteforce-wallet -t 8 -l 4 -m 4  bitcoin-wallet-backup-2014-11-19.dat

Error: couldn't open "main" database in "bitcoin-wallet-backup-2014-11-19.dat": Invalid argument
Error: couldn't find required info in wallet.

Is this file type supported?

**Comment by glv2** [comment]
The ```couldn't open "main" database in "bitcoin-wallet-backup-2014-11-19.dat"``` message seems to indicate that the Android app's backup file doesn't use the same format as the Bitcoin-Qt program (which is the only supported format so far).

**Comment by elkiwi** [comment]
Thanks for your reply...Salut!

**Comment by anywalletrecovery** [comment]
@elkiwi 
@bitnapper 
I have machine for android wallet recovery and can recover wallet password
Telegram: @walletrecover
