### ISSUE TITLE
string set cannot include !

### ISSUE THREAD

**Issue by PhillRob** [glv2/bruteforce-wallet#7]
special characters are often included in wallet passwords. the current code returns `-bash: !-: event not found`when `!`is included in the the charset.

**Comment by glv2** [comment]
To prevent *bash* from interpreting the ```!-``` sequence of characters as a *bash* command, you can try putting the charset between quotes or escaping the ```!```.

    bruteforce-wallet -s '123!-456' ...

or

    bruteforce-wallet -s 123\!-456 ...
