### ISSUE TITLE
will this work with dogecoin wallet?

### ISSUE THREAD

**Issue by chasecon** [glv2/bruteforce-wallet#9]
im getting a "ERROR: Couldn't find required info in wallet." when I try with my doge wallet

**Comment by glv2** [comment]
I tested the program with a wallet created with dogecoin-1.10.0 and it works.

The error you see could happen if the wallet file is not encrypted, or if there's an incompatibility between the version of the Berkeley DB library the wallet was created with and the version the bruteforce-wallet program was compiled with.

**Comment by chasecon** [comment]
What version do you think would be needed for a wallet from february,2014

**Comment by glv2** [comment]
Probably DB 4.8 or DB 5.1.

**Comment by anywalletrecovery** [comment]
I have machine for dogecoin wallet recovery and can recover wallet password
Telegram: @walletrecover

**Comment by anderson6470** [comment]
@chasecon 
I can recover your dogecoin wallet you can find me at walletsrecoveryservice@gmail.com
